server.port: 8087

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root
    password: password-1

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: NX5GNUOO026JPRP71CL5
  secretKey: s+hjbaLzdrQpxkVZBoreFkmNfwP+arK2ft1UtzFa
  bucketName: moviefun